import type { CurrencyCode, PaymentRequest, PaymentStatus, User } from "./types"

export const CURRENCY_META: Record<
  CurrencyCode,
  { symbol: string; label: string; locale: string; flag: string }
> = {
  EUR: { symbol: "€", label: "Euro", locale: "de-DE", flag: "EU" },
  BRL: { symbol: "R$", label: "Brazilian Real", locale: "pt-BR", flag: "BR" },
  USD: { symbol: "$", label: "US Dollar", locale: "en-US", flag: "US" },
  GBP: { symbol: "£", label: "British Pound", locale: "en-GB", flag: "GB" },
  JPY: { symbol: "¥", label: "Japanese Yen", locale: "ja-JP", flag: "JP" },
  INR: { symbol: "₹", label: "Indian Rupee", locale: "en-IN", flag: "IN" },
  KRW: { symbol: "₩", label: "South Korean Won", locale: "ko-KR", flag: "KR" },
  PLN: { symbol: "zł", label: "Polish Zloty", locale: "pl-PL", flag: "PL" },
  CAD: { symbol: "CA$", label: "Canadian Dollar", locale: "en-CA", flag: "CA" },
  AUD: { symbol: "A$", label: "Australian Dollar", locale: "en-AU", flag: "AU" },
  MXN: { symbol: "MX$", label: "Mexican Peso", locale: "es-MX", flag: "MX" },
  AED: { symbol: "د.إ", label: "UAE Dirham", locale: "ar-AE", flag: "AE" },
  SEK: { symbol: "kr", label: "Swedish Krona", locale: "sv-SE", flag: "SE" },
  ZAR: { symbol: "R", label: "South African Rand", locale: "en-ZA", flag: "ZA" },
  SGD: { symbol: "S$", label: "Singapore Dollar", locale: "en-SG", flag: "SG" },
}

// EUR -> local currency reference rates (used for the conversion estimate)
export const REFERENCE_RATES: Record<CurrencyCode, number> = {
  EUR: 1,
  BRL: 6.21,
  USD: 1.08,
  GBP: 0.84,
  JPY: 162.45,
  INR: 90.12,
  KRW: 1450.5,
  PLN: 4.32,
  CAD: 1.47,
  AUD: 1.65,
  MXN: 20.15,
  AED: 4.0,
  SEK: 11.5,
  ZAR: 20.5,
  SGD: 1.45,
}

export const STATUS_META: Record<
  PaymentStatus,
  { label: string; badge: string; dot: string }
> = {
  pending: {
    label: "Pending",
    badge: "border-status-pending-border bg-status-pending-bg text-status-pending-fg",
    // Bolinha usa um token de cor próprio e vívido (amarelo), não o fg de texto
    // que é escuro/turvo e se confundia com vermelho no tema claro.
    dot: "bg-status-pending-dot",
  },
  approved: {
    label: "Approved",
    badge: "border-status-approved-border bg-status-approved-bg text-status-approved-fg",
    dot: "bg-status-approved-dot",
  },
  rejected: {
    label: "Rejected",
    badge: "border-status-rejected-border bg-status-rejected-bg text-status-rejected-fg",
    dot: "bg-status-rejected-dot",
  },
  expired: {
    label: "Expired",
    badge: "border-border bg-muted text-muted-foreground",
    dot: "bg-muted-foreground",
  },
}

export const USERS: User[] = [
  {
    id: "u-fin",
    name: "Helena Marques",
    email: "finance@buzzvel.com",
    role: "finance",
    country: "Portugal",
    country_code: "PT",
    currency: "EUR",
  },
  {
    id: "u-br",
    name: "Rafael Souza",
    email: "rafael@buzzvel.com",
    role: "employee",
    country: "Brazil",
    country_code: "BR",
    currency: "BRL",
  },
  {
    id: "u-us",
    name: "Emily Carter",
    email: "emily@buzzvel.com",
    role: "employee",
    country: "United States",
    country_code: "US",
    currency: "USD",
  },
  {
    id: "u-gb",
    name: "Oliver Bennett",
    email: "oliver@buzzvel.com",
    role: "employee",
    country: "United Kingdom",
    country_code: "GB",
    currency: "GBP",
  },
  {
    id: "u-jp",
    name: "Yuki Tanaka",
    email: "yuki@buzzvel.com",
    role: "employee",
    country: "Japan",
    country_code: "JP",
    currency: "JPY",
  },
]

export function formatCurrency(amount: number, currency: CurrencyCode): string {
  const meta = CURRENCY_META[currency]
  return new Intl.NumberFormat(meta.locale, {
    style: "currency",
    currency,
    maximumFractionDigits: currency === "JPY" ? 0 : 2,
  }).format(amount)
}

export function formatDateTime(iso: string, locale = "en-GB"): string {
  return new Date(iso).toLocaleString(locale, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  })
}

export function formatDate(iso: string, locale = "en-GB"): string {
  return new Date(iso).toLocaleDateString(locale, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  })
}

export const PAYMENTS: PaymentRequest[] = [
  {
    id: "p-1001",
    reference: "PAY-2026-1001",
    user_id: "u-br",
    user_name: "Rafael Souza",
    country: "Brazil",
    currency: "BRL",
    local_amount: 4200,
    exchange_rate: 6.21,
    eur_amount: 676.33,
    status: "pending",
    created_at: "2026-06-12T09:24:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Equipment reimbursement — monitor and peripherals",
  },
  {
    id: "p-1002",
    reference: "PAY-2026-1002",
    user_id: "u-us",
    user_name: "Emily Carter",
    country: "United States",
    currency: "USD",
    local_amount: 1850,
    exchange_rate: 1.08,
    eur_amount: 1712.96,
    status: "approved",
    created_at: "2026-06-11T14:10:00Z",
    reviewed_at: "2026-06-11T16:42:00Z",
    rate_source: "exchangerate-api.com",
    description: "Tech conference — registration",
  },
  {
    id: "p-1003",
    reference: "PAY-2026-1003",
    user_id: "u-gb",
    user_name: "Oliver Bennett",
    country: "United Kingdom",
    currency: "GBP",
    local_amount: 920,
    exchange_rate: 0.84,
    eur_amount: 1095.24,
    status: "pending",
    created_at: "2026-06-12T07:55:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Design software — annual license",
  },
  {
    id: "p-1004",
    reference: "PAY-2026-1004",
    user_id: "u-jp",
    user_name: "Yuki Tanaka",
    country: "Japan",
    currency: "JPY",
    local_amount: 245000,
    exchange_rate: 162.45,
    eur_amount: 1508.16,
    status: "rejected",
    created_at: "2026-06-09T03:30:00Z",
    reviewed_at: "2026-06-09T11:05:00Z",
    rate_source: "exchangerate-api.com",
    description: "Corporate travel — accommodation",
  },
  {
    id: "p-1005",
    reference: "PAY-2026-1005",
    user_id: "u-br",
    user_name: "Rafael Souza",
    country: "Brazil",
    currency: "BRL",
    local_amount: 1300,
    exchange_rate: 6.18,
    eur_amount: 210.36,
    status: "expired",
    created_at: "2026-06-05T18:00:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Office supplies — pending for more than 48h",
  },
  {
    id: "p-1006",
    reference: "PAY-2026-1006",
    user_id: "u-us",
    user_name: "Emily Carter",
    country: "United States",
    currency: "USD",
    local_amount: 540,
    exchange_rate: 1.07,
    eur_amount: 504.67,
    status: "approved",
    created_at: "2026-06-08T12:20:00Z",
    reviewed_at: "2026-06-08T13:00:00Z",
    rate_source: "exchangerate-api.com",
    description: "Productivity tools subscription",
  },
  {
    id: "p-1007",
    reference: "PAY-2026-1007",
    user_id: "u-gb",
    user_name: "Oliver Bennett",
    country: "United Kingdom",
    currency: "GBP",
    local_amount: 2100,
    exchange_rate: 0.85,
    eur_amount: 2470.59,
    status: "pending",
    created_at: "2026-06-12T10:40:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "External consulting — product sprint",
  },
  {
    id: "p-1008",
    reference: "PAY-2026-1008",
    user_id: "u-br",
    user_name: "Rafael Souza",
    country: "Brazil",
    currency: "BRL",
    local_amount: 980,
    exchange_rate: 6.2,
    eur_amount: 158.06,
    status: "approved",
    created_at: "2026-06-07T11:15:00Z",
    reviewed_at: "2026-06-07T15:30:00Z",
    rate_source: "exchangerate-api.com",
    description: "Coworking desk — monthly",
  },
  {
    id: "p-1009",
    reference: "PAY-2026-1009",
    user_id: "u-jp",
    user_name: "Yuki Tanaka",
    country: "Japan",
    currency: "JPY",
    local_amount: 88000,
    exchange_rate: 161.9,
    eur_amount: 543.55,
    status: "approved",
    created_at: "2026-06-06T08:45:00Z",
    reviewed_at: "2026-06-06T10:20:00Z",
    rate_source: "exchangerate-api.com",
    description: "Online course — UX research",
  },
  {
    id: "p-1010",
    reference: "PAY-2026-1010",
    user_id: "u-us",
    user_name: "Emily Carter",
    country: "United States",
    currency: "USD",
    local_amount: 3200,
    exchange_rate: 1.09,
    eur_amount: 2935.78,
    status: "pending",
    created_at: "2026-06-12T13:05:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Laptop replacement — engineering",
  },
  {
    id: "p-1011",
    reference: "PAY-2026-1011",
    user_id: "u-gb",
    user_name: "Oliver Bennett",
    country: "United Kingdom",
    currency: "GBP",
    local_amount: 410,
    exchange_rate: 0.84,
    eur_amount: 488.1,
    status: "rejected",
    created_at: "2026-06-04T16:30:00Z",
    reviewed_at: "2026-06-05T09:10:00Z",
    rate_source: "exchangerate-api.com",
    description: "Client dinner — missing receipt",
  },
  {
    id: "p-1012",
    reference: "PAY-2026-1012",
    user_id: "u-br",
    user_name: "Rafael Souza",
    country: "Brazil",
    currency: "BRL",
    local_amount: 2750,
    exchange_rate: 6.22,
    eur_amount: 442.12,
    status: "pending",
    created_at: "2026-06-11T19:50:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Team offsite — venue deposit",
  },
  {
    id: "p-1013",
    reference: "PAY-2026-1013",
    user_id: "u-jp",
    user_name: "Yuki Tanaka",
    country: "Japan",
    currency: "JPY",
    local_amount: 162000,
    exchange_rate: 162.1,
    eur_amount: 999.38,
    status: "expired",
    created_at: "2026-06-03T05:20:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Hardware import — not reviewed in time",
  },
  {
    id: "p-1014",
    reference: "PAY-2026-1014",
    user_id: "u-us",
    user_name: "Emily Carter",
    country: "United States",
    currency: "USD",
    local_amount: 720,
    exchange_rate: 1.08,
    eur_amount: 666.67,
    status: "approved",
    created_at: "2026-06-05T10:00:00Z",
    reviewed_at: "2026-06-05T12:15:00Z",
    rate_source: "exchangerate-api.com",
    description: "Analytics tool — quarterly",
  },
  {
    id: "p-1015",
    reference: "PAY-2026-1015",
    user_id: "u-gb",
    user_name: "Oliver Bennett",
    country: "United Kingdom",
    currency: "GBP",
    local_amount: 1340,
    exchange_rate: 0.85,
    eur_amount: 1576.47,
    status: "approved",
    created_at: "2026-06-02T14:35:00Z",
    reviewed_at: "2026-06-02T17:00:00Z",
    rate_source: "exchangerate-api.com",
    description: "Accessibility audit — contractor",
  },
  {
    id: "p-1016",
    reference: "PAY-2026-1016",
    user_id: "u-br",
    user_name: "Rafael Souza",
    country: "Brazil",
    currency: "BRL",
    local_amount: 560,
    exchange_rate: 6.19,
    eur_amount: 90.47,
    status: "pending",
    created_at: "2026-06-12T06:10:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Mobile data plan — fieldwork",
  },
  {
    id: "p-1017",
    reference: "PAY-2026-1017",
    user_id: "u-jp",
    user_name: "Yuki Tanaka",
    country: "Japan",
    currency: "JPY",
    local_amount: 54000,
    exchange_rate: 162.6,
    eur_amount: 332.1,
    status: "approved",
    created_at: "2026-06-01T09:25:00Z",
    reviewed_at: "2026-06-01T11:40:00Z",
    rate_source: "exchangerate-api.com",
    description: "Books and references — design team",
  },
  {
    id: "p-1018",
    reference: "PAY-2026-1018",
    user_id: "u-us",
    user_name: "Emily Carter",
    country: "United States",
    currency: "USD",
    local_amount: 2480,
    exchange_rate: 1.07,
    eur_amount: 2317.76,
    status: "rejected",
    created_at: "2026-05-30T13:50:00Z",
    reviewed_at: "2026-05-31T08:30:00Z",
    rate_source: "exchangerate-api.com",
    description: "Premium seat upgrade — out of policy",
  },
  {
    id: "p-1019",
    reference: "PAY-2026-1019",
    user_id: "u-gb",
    user_name: "Oliver Bennett",
    country: "United Kingdom",
    currency: "GBP",
    local_amount: 175,
    exchange_rate: 0.84,
    eur_amount: 208.33,
    status: "approved",
    created_at: "2026-05-29T15:10:00Z",
    reviewed_at: "2026-05-29T16:05:00Z",
    rate_source: "exchangerate-api.com",
    description: "Domain renewal — design portfolio",
  },
  {
    id: "p-1020",
    reference: "PAY-2026-1020",
    user_id: "u-br",
    user_name: "Rafael Souza",
    country: "Brazil",
    currency: "BRL",
    local_amount: 6100,
    exchange_rate: 6.23,
    eur_amount: 979.13,
    status: "pending",
    created_at: "2026-06-12T15:20:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Conference sponsorship — booth",
  },
  {
    id: "p-1021",
    reference: "PAY-2026-1021",
    user_id: "u-jp",
    user_name: "Yuki Tanaka",
    country: "Japan",
    currency: "JPY",
    local_amount: 27500,
    exchange_rate: 162.0,
    eur_amount: 169.75,
    status: "approved",
    created_at: "2026-05-28T07:00:00Z",
    reviewed_at: "2026-05-28T09:45:00Z",
    rate_source: "exchangerate-api.com",
    description: "Stock photography — license",
  },
  {
    id: "p-1022",
    reference: "PAY-2026-1022",
    user_id: "u-us",
    user_name: "Emily Carter",
    country: "United States",
    currency: "USD",
    local_amount: 1290,
    exchange_rate: 1.08,
    eur_amount: 1194.44,
    status: "pending",
    created_at: "2026-06-11T17:35:00Z",
    reviewed_at: null,
    rate_source: "exchangerate-api.com",
    description: "Usability testing — participant fees",
  },
]
